### PR TITLE
Avoid showing "@ rb_sysopen" noise for Ruby 2.4.

### LINKED ISSUE #1071: features/docs/getting_started.feature:7 fails on Ruby 2.4.
## Summary

The test case features/docs/getting_started.feature:7 fails on Ruby 2.4:

## Expected Behavior

The test should pass.

## Current Behavior

~~~
expected "No such file or directory @ rb_sysopen - features. You can use `cucumber --init` to get started.\n" to include "No such file or directory - features. You can use `cucumber --init` to get started."
Diff:
@@ -1,2 +1,2 @@
-No such file or directory - features. You can use `cucumber --init` to get started.
+No such file or directory @ rb_sysopen - features. You can use `cucumber --init` to get started.
 (RSpec::Expectations::ExpectationNotMetError)
features/docs/getting_started.feature:10:in `Then it should fail with:'

Failing Scenarios:
cucumber features/docs/getting_started.feature:7 # Scenario: Run Cucumber in an empty directory
~~~

## Possible Solution

This obviously fails due to  https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/runtime.rb#L34 . Isn't it about the time to drop the https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/runtime.rb#L15 ? All currently supported Ruby prints this and I don't think it is going to change soon.

### PR DESCRIPTION
**Pull request by junaruga**
## Summary

This fixes #1071.

## Details

This issue happens for only Ruby 2.4.0.

## Motivation and Context

Want to pass tests.

## How Has This Been Tested?

```
$ ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]

$ bundle exec rake spec
...
568 examples, 0 failures

$ bundle exec rake cucumber
...
207 scenarios (17 failed, 190 passed)
1217 steps (17 failed, 1200 passed)
```

There are still failed tests. But they will be fixed by https://github.com/cucumber/cucumber-ruby/pull/1079 .
The `rb_sysopen` message was disappeared.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I've added tests for my code
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: lib/cucumber/runtime.rb [hunk 1]
```diff
@@ -30,8 +30,12 @@ def initialize(original_exception, path)
   class FileNotFoundException < FileException
   end
 
-  class FeatureFolderNotFoundException < FileException
-    include FixRuby21Bug9285 if Cucumber::RUBY_2_1 || Cucumber::RUBY_2_2 || Cucumber::RUBY_2_3
+  class FeatureFolderNotFoundException < Exception
+    attr :path
```
Comment (nodo) [inline lib/cucumber/runtime.rb]: Do we need a getter for the `path` variable here?

File: lib/cucumber/runtime.rb [hunk 2]
```diff
@@ -30,8 +30,12 @@ def initialize(original_exception, path)
...
+    def initialize(path)
```
Comment (nodo) [inline lib/cucumber/runtime.rb]: Do we need a getter for `path` variable here?

File: lib/cucumber/runtime.rb [hunk 3]
```diff
@@ -30,8 +30,12 @@ def initialize(original_exception, path)
...
+      super('No such file or directory - features')
+      @path = path
```
Comment (nodo) [inline lib/cucumber/runtime.rb]: Instead of calling `super`, I would suggest to override `message` method and output the path related to the error. E.g. `"Feature folder not found at #{@path}"` or similar. If we follow this path I would also use `File.expand_path(path)` for clarity.

File: lib/cucumber/platform.rb [hunk 4]
```diff
@@ -14,6 +14,7 @@ module Cucumber
     RUBY_2_2      = RUBY_VERSION =~ /^2\.2/
     RUBY_2_1      = RUBY_VERSION =~ /^2\.1/
     RUBY_2_3      = RUBY_VERSION =~ /^2\.3/
+    RUBY_2_4      = RUBY_VERSION =~ /^2\.4/
```
Comment (nodo) [inline lib/cucumber/platform.rb]: Do we need these constants at all? /cc @mattwynne @brasmusson

**Comment by nodo** [comment]
Thanks @junaruga - just added a couple of comments.

**Comment by junaruga** [comment]
@nodo ok, let me check your coments later. Thanks.

File: lib/cucumber/platform.rb (hunk 4 above)
Comment (mattwynne) [inline lib/cucumber/platform.rb]: I think this PR removes the only usage, so I'd say we can remove them.

Comment (nodo) [inline lib/cucumber/platform.rb]: Thanks @mattwynne 👍

**Comment by junaruga** [comment]
@nodo wait a moment. I will check it today or tomorrow as right now I am busy.

**Comment by nodo** [comment]
@junaruga no problem at all. Thanks for working on this!

File: lib/cucumber/runtime.rb (hunk 2 above)
Comment (junaruga) [inline lib/cucumber/runtime.rb]: @nodo I thought previously FeatureFolderNotFoundException had the getter for `path` variable, because it had extended `FileException`. But as we do not use the getter right now, removing it might be better. I am going to remove it.

File: lib/cucumber/runtime.rb (hunk 3 above)
Comment (junaruga) [inline lib/cucumber/runtime.rb]: @nodo ok I will follow your way.

File: lib/cucumber/platform.rb (hunk 4 above)
Comment (junaruga) [inline lib/cucumber/platform.rb]: @nodo ok I will remove them 👍

Comment (junaruga) [inline lib/cucumber/platform.rb]: > this PR removes the only usage,

I am still not sure above point. actually this PR can remove these constants?
or this PR should not touch these constants?

The constants RUBY_2_* are used in `gem_tasks/cucumber.rake`.

```
$ grep -r RUBY_2_ *
gem_tasks/cucumber.rake:                   elsif Cucumber::RUBY_2_0
gem_tasks/cucumber.rake:                   elsif Cucumber::RUBY_2_1
lib/cucumber/runtime.rb:    include FixRuby21Bug9285 if Cucumber::RUBY_2_1 || Cucumber::RUBY_2_2 || Cucumber::RUBY_2_3
lib/cucumber/platform.rb:    RUBY_2_2      = RUBY_VERSION =~ /^2\.2/
lib/cucumber/platform.rb:    RUBY_2_1      = RUBY_VERSION =~ /^2\.1/
lib/cucumber/platform.rb:    RUBY_2_3      = RUBY_VERSION =~ /^2\.3/
```

**Comment by junaruga** [comment]
@nodo I pushed one more commit for review. you can do "merge with squash" from Github GUI, when you will merge it. You can check the result on Travis too.

File: features/docs/getting_started.feature [hunk 5]
```diff
@@ -9,7 +9,7 @@ Feature: Getting started
     When I run `cucumber`
     Then it should fail with:
       """
-      No such file or directory - features. You can use `cucumber --init` to get started.
+      Feature folder not found at
       """
```
Comment (nodo) [inline features/docs/getting_started.feature]: I think this message should be more detailed. Some possible solutions:
1. Use `Aruba.config.root_directory` and somehow use it in the string
2. Change the exception to report a relative path and not a absolute path (so that here we can write `tmp/features`
3. Change the exception to not report the path

Sorry for this, I haven't notice this test before. However, I think it's important to keep it as informative as possible.

What do you think?

Comment (junaruga) [inline features/docs/getting_started.feature]: @nodo I like kind of 2. "kind of 2" means when I removed "File.expand_path", I did not need to add `tmp/features' to features/docs/getting_started.feature. Check my additional commit, I am going to push it right now.

I prefer `File.expand_path`.
But I like you would add `File.expand_path` by yourself later, if you need it.
Because right now I want to pass all the tests on Ruby 2.4.0.

**Comment by voxik** [comment]
The error message "Feature folder not found at features.", which is default output with this patch applied, is more confusing then helpful IMO. It is hardly obvious that the "features" refers to folder. If there was the dash as there used to be, that would be a bit better probably ....

**Comment by junaruga** [comment]
@nodo I changed and did rebase of my code. I do not change the message by myself on this PR.
I did not make it worse from current state for this PR. Maybe.

I like you will merge this, and ask you to improve the message by yourself after this PR as you like.

**Comment by junaruga** [comment]
@nodo I can tell you other options too.

- You can send your additional code to my repo https://github.com/junaruga/cucumber-ruby branch: `feature/fix-rb_sysopen-on-ruby-2.4`. I am going to accept your any code.
- You can close this pull-request. and you can fix it by yourself.

It does not matter for me. You can make a choice.

**Comment by nodo** [comment]
@junaruga sorry for not being responsive. I will check this PR as soon as possible. Thanks for your patience and for your work. Your changes looks good to me, I will just check the message as suggested by @voxik.

**Comment by junaruga** [comment]
@nodo Thank you!!
