### PR TITLE
Warn user when using space-separated string with cucumber_opts

### LINKED ISSUE #1614: Rake task fails with composite tag value option
**Describe the bug**

When cucumber rake task `cucumber_opts` field is a string and it contains composite tag option like `--tags 'not @skip'` cucumber rake task fails with `No such file or directory - @skip'. You can use `cucumber --init` to get started.` error.

**To Reproduce**
1. Create new cucumber rake task like this
   ```ruby
   desc 'Run features'
   Cucumber::Rake::Task.new(:features) do |t|
     t.cucumber_opts = "--tag 'not @skip'"
   end
   task :cucumber => :features
   ```
   Where `cucumber_opts` task property is set to a string value ends by composite tag option, `` for example
1. Run the rake task `bundle exec rake cucumber`
1. See error: ``No such file or directory - @skip'. You can use `cucumber --init` ``

**Expected behavior**

The rake task is running scenarios meets chosen tags criteria.
In the above example all scenarios except having `@skip` tag will run.

**Additional context**

Looks like the next split is a root cause of the issue: https://github.com/cucumber/cucumber-ruby/blob/3ebc762c3b9717e8593cd28f55ad356e287ebef6/lib/cucumber/rake/task.rb#L116

### PR DESCRIPTION
**Pull request by aurelien-reeves**
# Description

Fixes #1614 

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds new behaviour)

Please add an entry to the relevant section of CHANGELOG.md as part of this pull request.

### CODE REVIEW

**Review by valerianb — APPROVED** [review]

File: lib/cucumber/rake/task.rb [hunk 1]
```diff
@@ -113,7 +113,15 @@ def run
       attr_reader :cucumber_opts
 
       def cucumber_opts=(opts) # :nodoc:
-        @cucumber_opts = String == opts.class ? opts.split(' ') : opts
+        unless String == opts.class
+          @cucumber_opts = opts
```
Comment (luke-hill) [inline lib/cucumber/rake/task.rb:117]: can just be return @cucumber_opts = opts

File: lib/cucumber/rake/task.rb [hunk 2]
```diff
@@ -113,7 +113,15 @@ def run
       attr_reader :cucumber_opts
 
       def cucumber_opts=(opts) # :nodoc:
-        @cucumber_opts = String == opts.class ? opts.split(' ') : opts
+        unless String == opts.class
```
Comment (luke-hill) [inline lib/cucumber/rake/task.rb:116]: This should be opts.class == String (In rubocop it's referred to as yodacondition)

File: lib/cucumber/rake/task.rb [hunk 3]
```diff
@@ -113,7 +113,15 @@ def run
...
+          @cucumber_opts = opts
+          return
+        end
+
+        @cucumber_opts = opts.split(' ')
+        return if @cucumber_opts.length <= 1
+
+        $stderr.puts 'WARNING: consider using an array rather than a space-delimited string with cucumber_opts to avoid undesired behavior.'
```
Comment (luke-hill) [inline lib/cucumber/rake/task.rb:124]: Generic question. For all of our warnings we emit, do we use stderr or do we use some custom logger (I can't remember). i.e. for the deprecation stuff is this also the way we do it?

**Review by luke-hill — COMMENTED** [review]
Generic tidy-ups nothing breaking though

File: lib/cucumber/rake/task.rb (hunk 1 above)
Comment (aurelien-reeves) [reply lib/cucumber/rake/task.rb:117]: I did that first but it triggered a rubocop offense: Lint/ReturnInVoidContext

File: lib/cucumber/rake/task.rb (hunk 3 above)
Comment (aurelien-reeves) [reply lib/cucumber/rake/task.rb:124]: Yes, we use $stderr with all warnings (there are not that many actually :p)

File: lib/cucumber/rake/task.rb (hunk 2 above)
Comment (aurelien-reeves) [reply lib/cucumber/rake/task.rb:116]: Will change it
I actually copy/paste that from somewhere else in the code. Will take a look if there are a lot like that or not, maybe change all at once

Comment (aurelien-reeves) [reply lib/cucumber/rake/task.rb]: Done

File: lib/cucumber/rake/task.rb (hunk 3 above)
Comment (aurelien-reeves) [reply lib/cucumber/rake/task.rb:124]: With the deprecation helper, we default to $stderr, but there is the possibility to override it with a stream

File: lib/cucumber/rake/task.rb (hunk 1 above)
Comment (luke-hill) [reply lib/cucumber/rake/task.rb:117]: Yeh I think it's because you have a writer method here. Rubocop actually ignores this issue and admits there's a problem. So I'm happy with what you've done for now. Definitely a bit ugly but if the ruby style guide can't agree, there's no reason for us to go off.

**Comment by aurelien-reeves** [comment]
Thanks @luke-hill and @valerianb
