### PR TITLE
Fix #1017 - missing backtrace filter

### LINKED ISSUE #1017: Several test failing on Mac OS X / ruby 2.3.1 / rbenv 1.0.0
When running `bundle exec rake features` several tests fail on my machine.

```
$ bundle exec rake features
/usr/local/var/rbenv/versions/2.3.1/bin/ruby -S bundle exec cucumber
Using the default profile...
.................................F...........................................................................................................................F...............F....F.....................................F..................................................F.......................F.....F....F....F.........F.........................................................................................................................F......................................................................................................F.............................................................F........................................................................................................................................................F..........................................................................................................................................................................................................................................................................................................................................................................F.........F.........................................
```

All the tests fail with an error similar to the following:
```
bundle exec cucumber features/docs/cli/dry_run.feature                                                                                                1 ↵
Using the default profile...
..........F

(::) failed steps (::)

expected "Feature: test\n\n  Scenario:                      # features/test.feature:2\n    Given this step is ...fined$/) do\n  pending # Write code here that turns the phrase above into concrete actions\nend\n\n" to include "Feature: test\n\n  Scenario:                      # features/test.feature:2\n    Given this step is ...est.feature:3:in `Given this step is undefined'\n\n1 scenario (1 undefined)\n1 step (1 undefined)\n"
Diff:
@@ -1,2 +1,18 @@
-Feature: test\n\n  Scenario:                      # features/test.feature:2\n    Given this step is undefined # features/test.feature:3\n      Undefined step: "this step is undefined" (Cucumber::Undefined)\n      features/test.feature:3:in `Given this step is undefined'\n\n1 scenario (1 undefined)\n1 step (1 undefined)\n
+Feature: test
+
+  Scenario:                      # features/test.feature:2
+    Given this step is undefined # features/test.feature:3
+      Undefined step: "this step is undefined" (Cucumber::Undefined)
+      /usr/local/var/rbenv/versions/2.3.1/bin/bundle:23:in `load'
+      /usr/local/var/rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
+      features/test.feature:3:in `Given this step is undefined'
+
+1 scenario (1 undefined)
+1 step (1 undefined)
+
+You can implement step definitions for undefined steps with these snippets:
+
+Given(/^this step is undefined$/) do
+  pending # Write code here that turns the phrase above into concrete actions
+end
 (RSpec::Expectations::ExpectationNotMetError)
features/docs/cli/dry_run.feature:58:in `Then it should fail with:'
```

The test fail because of the extra lines:
```
/usr/local/var/rbenv/versions/2.3.1/bin/bundle:23:in `load'
/usr/local/var/rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
```

I am currently investigating this issue, but I would be really grateful to hear suggestion about it or to know whether I am missing something.

I am using ruby 2.3.1 with rbenv (1.0.0) and Mac OS X 10.11.6.

Failing Scenarios:
```
cucumber features/docs/cli/dry_run.feature:50 # Scenario: In strict mode with an undefined step
cucumber features/docs/cli/showing_differences.feature:8 # Scenario: Run single failing scenario with default diff enabled
cucumber features/docs/cli/strict_mode.feature:20 # Scenario: Fail with --strict due to undefined step
cucumber features/docs/cli/strict_mode.feature:35 # Scenario: Fail with --strict due to pending step
cucumber features/docs/defining_steps/nested_steps.feature:131 # Scenario: Undefined nested step
cucumber features/docs/defining_steps/table_diffing.feature:7 # Scenario: Extra row
cucumber features/docs/exception_in_after_step_hook.feature:24 # Scenario: Handle Exception in standard scenario step and carry on
cucumber features/docs/exception_in_after_step_hook.feature:57 # Scenario: Handle Exception in scenario outline table row and carry on
cucumber features/docs/exception_in_around_hook.feature:15 # Scenario: Exception before the test case is run
cucumber features/docs/exception_in_around_hook.feature:47 # Scenario: Exception after the test case is run
cucumber features/docs/exception_in_before_hook.feature:44 # Scenario: Handle Exception in Before hook for Scenario with Background
cucumber features/docs/formatters/json_formatter.feature:289 # Scenario: DocString
cucumber features/docs/formatters/junit_formatter.feature:178 # Scenario: pending and undefined steps with strict option should fail
cucumber features/docs/formatters/pretty_formatter.feature:31 # Scenario: Hook output should be printed before hook exception
cucumber features/docs/gherkin/background.feature:363 # Scenario: run a feature with a background that is pending
cucumber features/docs/writing_support_code/tagged_hooks.feature:34 # Scenario: omit tagged hook
cucumber features/docs/writing_support_code/tagged_hooks.feature:69 # Scenario: Omit example hook
```

### PR DESCRIPTION
**Pull request by nodo**
## Summary

- Add `.rbenv/.*/bin/bundle` to backtrace filters
- Refactor backtrace filtering
- Add unit tests for backtrace filtering

## Motivation and Context

It resolves https://github.com/cucumber/cucumber-ruby/issues/1017.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I've added tests for my code
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: lib/cucumber/formatter/backtrace_filter.rb [hunk 1]
```diff
@@ -4,13 +4,25 @@
...
+      lib/rspec
+      gems/
+      minitest
+      test/unit
+      .gem/ruby
+      lib/ruby/
+      rbenv/.*/bin/bundle
+    )
+
+    if ::Cucumber::JRUBY
```
Comment (mattwynne) [inline lib/cucumber/formatter/backtrace_filter.rb]: I wonder how helpful this line is - maybe we could just stick this in with the rest of them. WDYT?
