### PR TITLE
Respect Ruby configuration when filtering backtrace.

### LINKED ISSUE #1341: Ruby 2.6 compatibility issues on Fedora Rawhide
## Summary
nested Features / tests are failing, due to additional Ruby trace output with dynamic steps.

## Current Behavior
In comparison with the [expected output](https://github.com/cucumber/cucumber-ruby/blob/master/features/docs/defining_steps/nested_steps.feature), the output contains an entry from `forwardable.rb`:
~~~
+./features/step_definitions/steps2.rb:5:in `/I have a couple turtles/'
+/usr/share/ruby/forwardable.rb:230:in `invoke_dynamic_step'
+./features/step_definitions/steps2.rb:2:in `/two turtles/'
+features/test_feature_1.feature:3:in `Given two turtles'
~~~
and also here:
~~~
+  Scenario: Call directly
+    Given a step that calls an undefined step
+      Undefined dynamic step: "this does not exist" (Cucumber::UndefinedDynamicStep)
+      /usr/share/ruby/forwardable.rb:230:in `invoke_dynamic_step'
+      ./features/step_definitions/steps.rb:2:in `/^a step that calls an undefined step$/'
+      features/call_undefined_step_from_step_def.feature:4:in `Given a step that calls an undefined step'
+
+  Scenario: Call via another
+    Given a step that calls a step that calls an undefined step
+      Undefined dynamic step: "this does not exist" (Cucumber::UndefinedDynamicStep)
+      /usr/share/ruby/forwardable.rb:230:in `invoke_dynamic_step'
+      ./features/step_definitions/steps.rb:2:in `/^a step that calls an undefined step$/'
+      /usr/share/ruby/forwardable.rb:230:in `invoke_dynamic_step'
+      ./features/step_definitions/steps.rb:6:in `/^a step that calls a step that calls an undefined step$/'
+      features/call_undefined_step_from_step_def.feature:7:in `Given a step that calls a step that calls an undefined step'
~~~

As seen in our [Fedora build](https://copr-be.cloud.fedoraproject.org/results/pvalena/ruby26-gems/fedora-rawhide-x86_64/00843811-rubygem-cucumber/build.log.gz) ([failures only](https://paste.fedoraproject.org/paste/S7fGHAdF9xCIIxSOkQyadA)), during which we execute tests+features.

## Your Environment

* Version used: 3.1.2
* Operating System and version: Fedora Rawhide + Ruby 2.6.0
* Link to your project: http://fedoraproject.org/

### PR DESCRIPTION
**Pull request by voxik**
The Ruby might be configured to be installed into various locations. Be smarter about filtering backtrace to properly remove all traces of standard library.

Fixes #1341.

### CODE REVIEW

**Comment by voxik** [comment]
Ah, this obviously breaks the backtrace_filter test case. Not sure what is the most elegant way of fixing this ...

File: lib/cucumber/formatter/backtrace_filter.rb [hunk 1]
```diff
@@ -13,13 +13,15 @@ module Formatter
       minitest
       test/unit
       .gem/ruby
-      lib/ruby/
       bin/bundle
     ]
 
+    @backtrace_filters << RbConfig::CONFIG['rubyarchdir']
```
Comment (luke-hill) [inline lib/cucumber/formatter/backtrace_filter.rb]: we should probably use a conditional to only push in the one relevant to the platform. A bit like the JRuby one below

Comment (voxik) [reply lib/cucumber/formatter/backtrace_filter.rb]: This was my initial idea, then I went with the `#compact`. But I can modify the PR if you prefer the conditional.

**Comment by voxik** [comment]
> On Line7, can we rename this to something that hints these are the standard X-Platform locations

Not sure I understand. Do you propose to assign the RbConfig values to e.g. `ruby_stdlib_location` variable and then apply these to the `@backtrace_filters`?

File: lib/cucumber/formatter/backtrace_filter.rb (hunk 1 above)
Comment (luke-hill) [reply lib/cucumber/formatter/backtrace_filter.rb]: Ah I missed that. Urm My preference would be not to mix and match, so I think it would be better using a conditional as that's what is done above.

If you look in `cucumber/core/platform.rb` you can add some constants there if you'd prefer.

**Comment by voxik** [comment]
I have added conditionals instead of the compact. I briefly checked the `
cucumber/core/platform.rb` but it would IMHO be overcomplicated for this simple case.

**Comment by olleolleolle** [comment]
@voxik This is a helpful change to users - would you be able to rebase it? 

I added the label "Slow Burner" to the Issue this fixes.

**Comment by voxik** [comment]
This was mergable, but rebase and test against current master cannot harm, so here we go ;)

**Comment by luke-hill** [comment]
@voxik We've done a significant amount of changes to CI to try help builds across the ruby environments.

Accordingly some of your CI tests have failed. So we can try isolate the issues

**Comment by voxik** [comment]
The Ruby-2.2 and jruby failures are some gem dependency issues, unrelated to this PR as far as I can tell. I have not checked the others.

**Comment by luke-hill** [comment]
Agreed. 2.2 is failing for some silly reason which doesn't make sense and JRuby is failing for a reason that "shouldn't" occur, it's not installing the correct version of protobuf.

The publish build failed for jobs. These kind of things shouldn't really be happening, although I'm not sure on how to setup the circle-ci stuff, but yes, these are all false failures annoyingly.

**Comment by olleolleolle** [comment]
@luke-hill Can we get agreement on merging this - even though 2.2 is failing?

(The JRuby failing is something we know the reason for.)

**Comment by luke-hill** [comment]
I'll go through all the failures this morning and if they're all known ones I'll merge it. Figure we can deal with the breakout stuff as breakout items.

**Comment by luke-hill** [comment]
Merging as agreed with @olleolleolle about breakout tasks existing to fix up other items.

**Comment by aslakhellesoy** [comment]
Hi @voxik,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by olleolleolle** [comment]
Thanks, @voxik and @luke-hill for patience, good humor and hard work!

**Comment by aslakhellesoy** [comment]
Hi @voxik,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber
